#include "enum.hpp"


City getCityEnum(const std::string& cityName) {
    static std::unordered_map<std::string, City> cityMap = {
        {"Adana", Adana},
        {"Adiyaman", Adiyaman},
        {"Afyonkarahisar", Afyonkarahisar},
        {"Agri", Agri},
        {"Amasya", Amasya},
        {"Ankara", Ankara},
        {"Antalya", Antalya},
        {"Artvin", Artvin},
        {"Aydin", Aydin},
        {"Balikesir", Balikesir},
        {"Bilecik", Bilecik},
        {"Bingol", Bingol},
        {"Bitlis", Bitlis},
        {"Bolu", Bolu},
        {"Burdur", Burdur},
        {"Bursa", Bursa},
        {"Canakkale", Canakkale},
        {"Cankiri", Cankiri},
        {"Corum", Corum},
        {"Denizli", Denizli},
        {"Diyarbakir", Diyarbakir},
        {"Edirne", Edirne},
        {"Elazig", Elazig},
        {"Erzincan", Erzincan},
        {"Erzurum", Erzurum},
        {"Eskisehir", Eskisehir},
        {"Gaziantep", Gaziantep},
        {"Giresun", Giresun},
        {"Gumushane", Gumushane},
        {"Hakkari", Hakkari},
        {"Hatay", Hatay},
        {"Isparta", Isparta},
        {"Icel", Icel},
        {"Istanbul", Istanbul},
        {"Izmir", Izmir},
        {"Kars", Kars},
        {"Kastamonu", Kastamonu},
        {"Kayseri", Kayseri},
        {"Kirklareli", Kirklareli},
        {"Kirsehir", Kirsehir},
        {"Kocaeli", Kocaeli},
        {"Konya", Konya},
        {"Kutahya", Kutahya},
        {"Malatya", Malatya},
        {"Manisa", Manisa},
        {"Kahramanmaras", Kahramanmaras},
        {"Mardin", Mardin},
        {"Mugla", Mugla},
        {"Mus", Mus},
        {"Nevsehir", Nevsehir},
        {"Nigde", Nigde},
        {"Ordu", Ordu},
        {"Rize", Rize},
        {"Sakarya", Sakarya},
        {"Samsun", Samsun},
        {"Siirt", Siirt},
        {"Sinop", Sinop},
        {"Sivas", Sivas},
        {"Tekirdag", Tekirdag},
        {"Tokat", Tokat},
        {"Trabzon", Trabzon},
        {"Tunceli", Tunceli},
        {"Sanliurfa", Sanliurfa},
        {"Usak", Usak},
        {"Van", Van},
        {"Yozgat", Yozgat},
        {"Zonguldak", Zonguldak},
        {"Aksaray", Aksaray},
        {"Bayburt", Bayburt},
        {"Karaman", Karaman},
        {"Kirikkale", Kirikkale},
        {"Batman", Batman},
        {"Sirnak", Sirnak},
        {"Bartin", Bartin},
        {"Ardahan", Ardahan},
        {"Igdir", Igdir},
        {"Yalova", Yalova},
        {"Karabuk", Karabuk},
        {"Kilis", Kilis},
        {"Osmaniye", Osmaniye},
        {"Duzce", Duzce}
    };

    auto it = cityMap.find(cityName);
    if (it != cityMap.end()) {
        return it->second;
    } else {
        // Return an 'invalid' enum value or handle the case as needed
        return TOTAL_CITIES; // For example purposes, indicating an invalid city
    }
}