#include "enum.hpp"


City getCityEnum(const std::string& cityName) {
    static std::unordered_map<std::string, City> cityMap = {
        {"Adana", Adana},
        {"Adiyaman", Adiyaman},
        {"Afyonkarahisar", Afyonkarahisar},
        {"Agri", Agri},
        {"Amasya", Amasya},
        {"Ankara", Ankara},
        {"Antalya", Antalya},
        {"Artvin", Artvin},
        {"Aydin", Aydin},
        {"Balikesir", Balikesir},
        {"Bilecik", Bilecik},
        {"Bingol", Bingol},
        {"Bitlis", Bitlis},
        {"Bolu", Bolu},
        {"Burdur", Burdur},
        {"Bursa", Bursa},
        {"Canakkale", Canakkale},
        {"Cankiri", Cankiri},
        {"Corum", Corum},
        {"Denizli", Denizli},
        {"Diyarbakir", Diyarbakir},
        {"Edirne", Edirne},
        {"Elazig", Elazig},
        {"Erzincan", Erzincan},
        {"Erzurum", Erzurum},
        {"Eskisehir", Eskisehir},
        {"Gaziantep", Gaziantep},
        {"Giresun", Giresun},
        {"Gumushane", Gumushane},
        {"Hakkari", Hakkari},
        {"Hatay", Hatay},
        {"Isparta", Isparta},
        {"Icel", Icel},
        {"Istanbul", Istanbul},
        {"Izmir", Izmir},
        {"Kars", Kars},
        {"Kastamonu", Kastamonu},
        {"Kayseri", Kayseri},
        {"Kirklareli", Kirklareli},
        {"Kirsehir", Kirsehir},
        {"Kocaeli", Kocaeli},
        {"Konya", Konya},
        {"Kutahya", Kutahya},
        {"Malatya", Malatya},
        {"Manisa", Manisa},
        {"Kahramanmaras", Kahramanmaras},
        {"Mardin", Mardin},
        {"Mugla", Mugla},
        {"Mus", Mus},
        {"Nevsehir", Nevsehir},
        {"Nigde", Nigde},
        {"Ordu", Ordu},
        {"Rize", Rize},
        {"Sakarya", Sakarya},
        {"Samsun", Samsun},
        {"Siirt", Siirt},
        {"Sinop", Sinop},
        {"Sivas", Sivas},
        {"Tekirdag", Tekirdag},
        {"Tokat", Tokat},
        {"Trabzon", Trabzon},
        {"Tunceli", Tunceli},
        {"Sanliurfa", Sanliurfa},
        {"Usak", Usak},
        {"Van", Van},
        {"Yozgat", Yozgat},
        {"Zonguldak", Zonguldak},
        {"Aksaray", Aksaray},
        {"Bayburt", Bayburt},
        {"Karaman", Karaman},
        {"Kirikkale", Kirikkale},
        {"Batman", Batman},
        {"Sirnak", Sirnak},
        {"Bartin", Bartin},
        {"Ardahan", Ardahan},
        {"Igdir", Igdir},
        {"Yalova", Yalova},
        {"Karabuk", Karabuk},
        {"Kilis", Kilis},
        {"Osmaniye", Osmaniye},
        {"Duzce", Duzce}
    };

    auto it = cityMap.find(cityName);
    if (it != cityMap.end()) {
        return it->second;
    } else {
        // Return an 'invalid' enum value or handle the case as needed
        return TOTAL_CITIES; // For example purposes, indicating an invalid city
    }
}

std::string num_to_city(const size_t& num) {
    static std::map<int, std::string> cityMap = {
        {0, "Adana"},
        {1, "Adiyaman"},
        {2, "Afyonkarahisar"},
        {3, "Agri"},
        {4, "Amasya"},
        {5, "Ankara"},
        {6, "Antalya"},
        {7, "Artvin"},
        {8, "Aydin"},
        {9, "Balikesir"},
        {10, "Bilecik"},
        {11, "Bingol"},
        {12, "Bitlis"},
        {13, "Bolu"},
        {14, "Burdur"},
        {15, "Bursa"},
        {16, "Canakkale"},
        {17, "Cankiri"},
        {18, "Corum"},
        {19, "Denizli"},
        {20, "Diyarbakir"},
        {21, "Edirne"},
        {22, "Elazig"},
        {23, "Erzincan"},
        {24, "Erzurum"},
        {25, "Eskisehir"},
        {26, "Gaziantep"},
        {27, "Giresun"},
        {28, "Gumushane"},
        {29, "Hakkari"},
        {30, "Hatay"},
        {31, "Isparta"},
        {32, "Icel"},
        {33, "Istanbul"},
        {34, "Izmir"},
        {35, "Kars"},
        {36, "Kastamonu"},
        {37, "Kayseri"},
        {38, "Kirklareli"},
        {39, "Kirsehir"},
        {40, "Kocaeli"},
        {41, "Konya"},
        {42, "Kutahya"},
        {43, "Malatya"},
        {44, "Manisa"},
        {45, "Kahramanmaras"},
        {46, "Mardin"},
        {47, "Mugla"},
        {48, "Mus"},
        {49, "Nevsehir"},
        {50, "Nigde"},
        {51, "Ordu"},
        {52, "Rize"},
        {53, "Sakarya"},
        {54, "Samsun"},
        {55, "Siirt"},
        {56, "Sinop"},
        {57, "Sivas"},
        {58, "Tekirdag"},
        {59, "Tokat"},
        {60, "Trabzon"},
        {61, "Tunceli"},
        {62, "Sanliurfa"},
        {63, "Usak"},
        {64, "Van"},
        {65, "Yozgat"},
        {66, "Zonguldak"},
        {67, "Aksaray"},
        {68, "Bayburt"},
        {69, "Karaman"},
        {70, "Kirikkale"},
        {71, "Batman"},
        {72, "Sirnak"},
        {73, "Bartin"},
        {74, "Ardahan"},
        {75, "Igdir"},
        {76, "Yalova"},
        {77, "Karabuk"},
        {78, "Kilis"},
        {79, "Osmaniye"},
        {80, "Duzce"}
    };

    auto it = cityMap.find(num);
    if (it != cityMap.end()) {
        return it->second;
    } else {
        // Return an 'invalid' enum value or handle the case as needed
        return "None"; // For example purposes, indicating an invalid city
    }
}